[package]
name = "refsafety-diff-driver"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
arbitrary = { workspace = true, features = ["derive"] }
move-bytecode-verifier.workspace = true
move-bytecode-verifier-meter.workspace = true
move-vm-config.workspace = true
move-core-types = { workspace = true, features = ["fuzzing"] }
move-binary-format = { workspace = true, features = ["fuzzing"] }

[[bin]]
name = "diff_driver"
path = "src/main.rs"

[[bin]]
name = "guided_driver"
path = "src/guided.rs"
